name: Update GitHub Streak Widget

on:
  schedule:
    - cron: "0 2 * * *" # Runs daily at 2:00 AM UTC
  workflow_dispatch: # Allows manual triggering

jobs:
  fetch-streak:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Ensure assets directory exists
        run: mkdir -p assets

      - name: Fetch Streak Widget
        run: |
          curl -s -o assets/streak.svg \
          "https://github-readme-streak-stats.herokuapp.com?user=${{ github.repository_owner }}&theme=dark&hide_title=true&hide_border=true&token=${{ secrets.GH_STATS_TOKEN }}"

      - name: Commit and Push
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add assets/streak.svg
          git commit -m "chore: update streak widget" || echo "No changes to commit"
          git push
