name: Update GitHub Streak Widget

on:
  schedule:
    - cron: "0 2 * * *" # Runs daily at 2:00 AM UTC
  workflow_dispatch: # Allows manual triggering

permissions:
  contents: write # ✅ This allows pushing commits

jobs:
  fetch-streak:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Ensure assets directory exists
        run: mkdir -p assets

      - name: Fetch Streak Widget
        run: |
          mkdir -p assets
          curl -s -H "User-Agent: Mozilla/5.0" \
            -w "%{http_code}" -o temp_streak.svg \
            "https://github-readme-streak-stats.herokuapp.com?user=${{ github.repository_owner }}&theme=dark&hide_title=true&token=${{ secrets.GH_STATS_TOKEN }}" > status.txt

          code=$(cat status.txt)
          if [ "$code" = "200" ]; then
            mv temp_streak.svg assets/streak.svg
          else
            echo "⚠️ curl returned HTTP $code – streak.svg not updated"
            rm -f temp_streak.svg
          fi
          rm -f status.txt
      - name: Commit and Push
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add assets/streak.svg
          git commit -m "chore: update streak widget" || echo "No changes to commit"
          git push
